### ISSUE TITLE
Relation to nb_conda and co

### ISSUE THREAD

**Issue by betatim** [techtocore/Jupyter-Package-Manager#2]
Hey 👋 ,

I saw this repo mentioned in a newsletter and a question that came up was how this fits with existing extensions like https://github.com/Anaconda-Platform/nb_conda?

Good luck!

**Comment by techtocore** [comment]
Hey,

Glad that you found this repo. This project is supposed to handle 'projects', while the nb_conda extension primarily deals with managing conda environments. However, each project is mapped to an environment under the hood. Hope this clarifies your question.

Thanks and Regards

**Comment by fcollonval** [comment]
Hey, I came through the same channel than @betatim. And was wondering the same. Thx for the answer.

I forked nb_conda mainly to have it [included in Jupyterlab](https://github.com/fcollonval/jupyter_conda).
@techtocore I was wondering if it makes sense to merge the two projects and optimize the effort?
